apiVersion: apps/v1
kind: ReplicaSet
metadata:
  annotations:
    deployment.kubernetes.io/desired-replicas: "1"
    deployment.kubernetes.io/max-replicas: "2"
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2022-09-14T18:42:08Z"
  generation: 1
  labels:
    app: jenkins
    pod-template-hash: 65f6cc78c9
  name: jenkins-65f6cc78c9
  namespace: jenkins
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: Deployment
    name: jenkins
    uid: 3527b338-0de4-49fb-8bdb-bd7872f02cec
  resourceVersion: "294431"
  uid: 4479dca6-8735-49e5-b411-071a1d88df31
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
      pod-template-hash: 65f6cc78c9
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jenkins
        pod-template-hash: 65f6cc78c9
    spec:
      containers:
      - image: jenkins/jenkins:lts-jdk11
        imagePullPolicy: IfNotPresent
        name: jenkins
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 3Gi
          requests:
            cpu: 500m
            memory: 500Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: jenkins-home
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: jenkins-home
status:
  availableReplicas: 1
  fullyLabeledReplicas: 1
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
